"""
Comparison & Report API — document comparison and PDF report export.
"""

from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from agents.comparison_agent import compare_documents
from agents.summarization_agent import get_summary
from agents.extraction_agent import extract_data
from services.rag_service import generate_insights
from database.db import get_db
from bson import ObjectId
from services.auth_middleware import get_current_user
import io
import json

router = APIRouter(tags=["Comparison & Reports"])


class CompareRequest(BaseModel):
    doc_id_1: str
    doc_id_2: str


@router.post("/compare-documents")
async def compare_documents_endpoint(request: CompareRequest, current_user: dict = Depends(get_current_user)):
    """
    Compare two documents and return structured analysis with
    similarities, differences, and recommendations.
    """
    try:
        result = await compare_documents(request.doc_id_1, request.doc_id_2)
        return result
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Comparison failed: {str(e)}")


@router.get("/export-report/{document_id}")
async def export_report_as_text(document_id: str, current_user: dict = Depends(get_current_user)):
    """
    Generate and export a full AI insights report as a downloadable text file.
    """
    db = get_db()
    doc = await db.documents.find_one({"_id": ObjectId(document_id)})
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    try:
        summary_result = await get_summary(document_id)
        extraction_result = await extract_data(document_id)
        text = doc.get("text_content", "")
        classification = doc.get("classification")
        insights = await generate_insights(text, classification)

        # Build report
        report_lines = [
            "=" * 60,
            "  AI DOCUMENT INTELLIGENCE REPORT",
            "=" * 60,
            "",
            f"Document: {doc.get('original_name', 'Unknown')}",
            f"Classification: {classification or 'Unknown'}",
            f"Chunks: {doc.get('chunk_count', 0)}",
            "",
            "-" * 40,
            "  SUMMARY",
            "-" * 40,
            summary_result.get("summary", "N/A"),
            "",
            "-" * 40,
            "  EXTRACTED DATA",
            "-" * 40,
            json.dumps(extraction_result.get("extracted_data", {}), indent=2),
            "",
            "-" * 40,
            "  AI INSIGHTS",
            "-" * 40,
        ]
        for i, insight in enumerate(insights, 1):
            report_lines.append(f"  {i}. {insight}")

        report_lines.extend(["", "=" * 60, "  Generated by AI Document Intelligence Platform", "=" * 60])

        report_text = "\n".join(report_lines)

        # Return as downloadable file
        buffer = io.BytesIO(report_text.encode("utf-8"))
        filename = f"report_{doc.get('original_name', 'document').rsplit('.', 1)[0]}.txt"

        return StreamingResponse(
            buffer,
            media_type="text/plain",
            headers={"Content-Disposition": f"attachment; filename={filename}"},
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Report export failed: {str(e)}")
